# Generated by Django 4.1.5 on 2023-01-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='number_of_fails',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
