# Generated by Django 4.1.5 on 2023-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_alter_request_result_alter_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='counted',
            field=models.BooleanField(default=False),
        ),
    ]
